version: '3.7'

services:
  app:
    image: langgenius/dify:latest
    container_name: dify-app
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - APP_ENV=production
      - DATABASE_URL=sqlite:///app/data/db.sqlite3
      - ALLOW_SIGNUP=true
